#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/maria/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/maria/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/maria/maja/articles/lfp_phd/final code/data/HallermannEtAl2012/x86_64/.libs/libnrnmech.so" "$@"
